---
##########################################################
# ansible

ansible_become: true
ansible_become_user: root

##########################################################
# images

docker_registry: quay.io
openstack_release: victoria
kolla_image_version: "{{ openstack_release }}"

##########################################################
# kolla

kolla_enable_sanity_checks: "yes"

##########################################################
# haproxy

kolla_internal_fqdn: api-int.osism.test
kolla_external_fqdn: api.osism.test

kolla_enable_tls_external: "no"
kolla_enable_tls_internal: "no"

##########################################################
# openstack

# enable services
enable_aodh: "yes"
enable_barbican: "yes"
enable_ceilometer: "yes"
enable_cinder: "yes"
enable_cinder_backup: "yes"
enable_designate: "yes"
enable_gnocchi: "yes"
enable_heat: "yes"
enable_magnum: "yes"
enable_manila: "yes"
enable_octavia: "yes"
enable_panko: "yes"
enable_senlin: "yes"

enable_etcd: "yes"
enable_grafana: "yes"
enable_prometheus: "yes"
enable_redis: "yes"
enable_skydive: "yes"

# disable services

# generic

openstack_service_workers: 2

# profiling
enable_osprofiler: "no"

# elasticsearch

es_heap_size: "1g"

# mariadb

enable_mariabackup: "yes"

# rabbitmq

rabbitmq_server_additional_erl_args: "+S 1:1"

# horizon
horizon_backend_database: "yes"

# keystone
keystone_token_provider: "fernet"
keystone_public_url: "http://api.osism.test:5000"
enable_keystone_federation: "yes"
keystone_identity_providers:
  - name: "gx-scs"
    openstack_domain: "default"
    protocol: "openid"
    identifier: "http://api.osism.test:8170/auth/realms/gx-scs"
    public_name: "Authenticate via gx-scs"
    attribute_mapping: "mappingId1"
    metadata_folder: "/var/lib/kolla/config_files/metadata_folder"
    certificate_file: "/var/lib/kolla/config_files/XsKLq7AkttlFsul9ccGnY92Xi_Y7D9AoQ9SSGldL_f0.pem"
keystone_trusted_dashboards:
  - "http://api.osism.test/auth/websso/"
keystone_remote_id_attribute_oidc: "HTTP_OIDC_ISS"
keystone_enable_federation_openid: "yes"
# keystone_enable_federation_openid: "{{ enable_keystone_federation | bool and keystone_identity_providers | selectattr('protocol','equalto','openid') | list | count > 0 }}"
keystone_federation_openid_crypto_password: "openstack"
keystone_federation_oidc_scopes: "openid email profile"
keystone_container_federation_oidc_metadata_url: "http://testbed-manager.osism.test:8170/auth/realms/gx-scs/.well-known/openid-configuration"
keystone_container_federation_oidc_client_id: "keystone"
## The next line is just an example from a manual Keycloak installation in the testbed and needs to be fixed.
## See the openstack wallaby commit https://github.com/openstack/kolla-ansible/commit/f3fbe8370
## for how it should be done properly:
keystone_federation_openid_certificate_key_ids: "XsKLq7AkttlFsul9ccGnY92Xi_Y7D9AoQ9SSGldL_f0#/etc/apache2/cert/gx-scs-keystone.pem"

keystone_identity_mappings:
  - name: "mappingId1"
    file: "/var/lib/kolla/config_files/keystone/federation/oidc/attribute_maps/oidc_attribute_mappingId1.json"


# neutron
neutron_plugin_agent: "{{ 'ovn' if openstack_release in ['ussuri', 'victoria'] else 'openvswitch' }}"

enable_neutron_agent_ha: "yes"
enable_neutron_dvr: "no"
enable_neutron_qos: "yes"

# nova
nova_console: novnc
nova_virt_type: kvm

# octavia
octavia_network_type: tenant
octavia_loadbalancer_topology: "ACTIVE_STANDBY"

# ceilometer
ceilometer_database_type: gnocchi
ceilometer_event_type: panko

# designate
designate_ns_record: openstack.osism.test

# magnum
enable_cluster_user_trust: "yes"

# manila
enable_manila_backend_generic: "yes"

# prometheus
enable_prometheus_server: "no"

##########################################################
# external ceph

enable_ceph: "no"

cinder_backend_ceph: "yes"
glance_backend_ceph: "yes"
gnocchi_backend_storage: "ceph"
nova_backend_ceph: "yes"

ceph_gnocchi_pool_name: "metrics"
ceph_nova_keyring: ceph.client.nova.keyring
cinder_backup_driver: "ceph"
glance_backend_file: "no"

# NOTE: public_network from environments/ceph/configuration.yml
ceph_public_network: 192.168.64.0/20

##########################################################
# other
