---
- name: Apply role osism.manager
  hosts: localhost
  connection: local
  gather_facts: true

  vars_files:
    - /opt/configuration/inventory/host_vars/testbed-manager.osism.local.yml
    - /opt/configuration/environments/manager/configuration.yml
    - /opt/configuration/environments/manager/images.yml
    - /opt/configuration/environments/manager/secrets.yml
    - /opt/configuration/environments/secrets.yml

  roles:
    - ansible-manager
