---
- name: Apply role osism.configuration
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    configuration_git_version: master
    configuration_git_host: github.com
    configuration_git_port: 443
    configuration_git_repository: osism/testbed.git
    configuration_git_protocol: https

  roles:
    - ansible-configuration

- name: Apply role osism.manager
  hosts: localhost
  connection: local
  gather_facts: true

  vars_files:
    - /opt/configuration/inventory/host_vars/testbed-manager.osism.local.yml
    - /opt/configuration/environments/manager/configuration.yml
    - /opt/configuration/environments/manager/images.yml
    - /opt/configuration/environments/manager/secrets.yml
    - /opt/configuration/environments/secrets.yml

  roles:
    - ansible-manager
