---
- hosts: localhost
  connection: local
  gather_facts: true

  vars:
    # ansible-common
    cleanup_services_common:
      - NetworkManager
      - iscsid
      - lxcfs
      - nscd
      - ntp
    cleanup_packages_common:
      - apport
      - apport-symptoms
      - dosfstools
      - libvirt-bin
      - lxc
      - lxd
      - ntfs-3g
      - open-iscsi
      - popularity-contest
      - python3-apport
      - snapd
      - telnet
      - ubuntu-server
      - xauth
    rng_enable_common: yes
    smartd_enable_common: no

    # ansible-docker
    docker_user: dragon
    docker_configure_repository: no
    docker_configure_storage_driver: yes
    docker_storage_driver: overlay2

    # ansible-operator
    operator_user: dragon
    operator_group: dragon
    operator_authorized_keys:
      - "{{lookup('file', '/home/ubuntu/.ssh/id_rsa.pub')}}"

    # ansible-repository
    repository_cache_valid_time: 0
    repository_key_ids: {}
    repositories:
      - name: "{{ ansible_distribution_release }}-docker"
        repository: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      - name: "{{ ansible_distribution_release }}-netdata"
        repository: "deb [arch=amd64] https://packagecloud.io/netdata/netdata-edge/ubuntu/ {{ ansible_distribution_release }} main"
      - name: "{{ ansible_distribution_release }}"
        repository: "deb [arch=amd64] http://de.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} main restricted universe multiverse"
      - name: "{{ ansible_distribution_release }}-backports"
        repository: "deb [arch=amd64] http://de.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-backports main restricted universe multiverse"
      - name: "{{ ansible_distribution_release }}-security"
        repository: "deb [arch=amd64] http://de.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-security main restricted universe multiverse"
      - name: "{{ ansible_distribution_release }}-updates"
        repository: "deb [arch=amd64] http://de.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates main restricted universe multiverse"

    # ansible-hardening
    stig_version: rhel7
    security_rhel7_enable_chrony: no
    security_rhel7_enable_linux_security_module: no
    security_rhel7_remove_shosts_files: yes
    security_package_clean_on_remove: yes
    security_rhel7_automatic_package_updates: no
    security_rhel7_session_timeout: 3600
    security_sshd_allowed_macs: hmac-sha2-256,hmac-sha2-512,hmac-sha1

  roles:
    - ansible-resolvconf
    - ansible-chrony
    - ansible-repository
    - ansible-common
    - ansible-operator
    - ansible-docker
    - ansible-hardening
